# DUplique e renomeie para application-local.properties e adicione as suas configurações locais

# Datasource connect
spring.datasource.url=datasource-url
spring.datasource.username=datasource-username
spring.datasource.password=datasource-password

# Groq key
spring.ai.openai.api-key=openai-api-key