package com.smarterfit.util.mapper;

import com.smarterfit.dto.request.ClassGroupRequestDTO;
import com.smarterfit.dto.response.ClassGroupResponseDTO;
import com.smarterfit.exception.ResourceNotFoundException;
import com.smarterfit.model.ClassGroup;
import com.smarterfit.model.Modality;
import com.smarterfit.model.User;

public class ClassGroupMapper {

    private ClassGroupMapper() {
        // Private constructor to prevent instantiation
    }

    public static ClassGroup toEntity(ClassGroupRequestDTO dto, ClassGroup classGroup, Modality modality,
                                      User creator) {
        if (dto == null) {
            throw new ResourceNotFoundException("ClassGroup not found.");
        }

        classGroup.setTitle(dto.title());
        classGroup.setCapacity(dto.capacity());
        classGroup.setModality(modality);
        classGroup.setDescription(dto.description());
        classGroup.setStartDate(dto.startDate());
        classGroup.setEndDate(dto.endDate());
        classGroup.setCreatedByUser(creator);
        classGroup.setAutoGeneratedSessions(dto.autoGeneratedSessions());


        return classGroup;
    }

    public static ClassGroup toEntity(ClassGroupRequestDTO dto, Modality modality, User creator) {
        return toEntity(dto, new ClassGroup(), modality, creator);
    }

    public static ClassGroupResponseDTO toResponse(ClassGroup classGroup, String nameCreator) {


        return new ClassGroupResponseDTO(
                classGroup.getId(),
                classGroup.getTitle(),
                classGroup.getCapacity(),
                classGroup.getDescription(),
                ModalityMapper.toResponse(classGroup.getModality()),
                classGroup.getStartDate(),
                classGroup.getEndDate(),
                nameCreator
        );
    }



}
