package com.smarterfit.util.mapper;

import com.smarterfit.dto.request.ClassGroupRequestDTO;
import com.smarterfit.dto.request.ModalityRequestDTO;
import com.smarterfit.dto.response.ClassGroupResponseDTO;
import com.smarterfit.dto.response.ClassGroupScheduleResponseDTO;
import com.smarterfit.dto.response.ModalityResponseDTO;
import com.smarterfit.enums.GroupType;
import com.smarterfit.exception.ResourceNotFoundException;
import com.smarterfit.model.ClassGroup;
import com.smarterfit.model.ClassGroupSchedule;
import com.smarterfit.model.Modality;
import com.smarterfit.model.User;
import com.smarterfit.util.Converter;

import java.util.List;
import java.util.stream.Collectors;

public class ClassGroupMapper {

    private ClassGroupMapper() {
        // Private constructor to prevent instantiation
    }

    public static ClassGroup toEntity(ClassGroupRequestDTO dto, ClassGroup classGroup, Modality modality,
                                      User creator) {
        if (dto == null) {
            throw new ResourceNotFoundException("ClassGroup not found.");
        }

        classGroup.setName(dto.name());
        classGroup.setCapacity(dto.capacity());
        classGroup.setModality(modality);
        classGroup.setGroupType(Converter.stringToEnum(GroupType.class, dto.groupType()));
        classGroup.setDescription(dto.description());
        classGroup.setStartDate(dto.startDate());
        classGroup.setEndDate(dto.endDate());
        classGroup.setAutoGeneratedSessions(dto.autoGeneratedSessions());
        classGroup.setUser(creator);


        return classGroup;
    }

    public static ClassGroup toEntity(ClassGroupRequestDTO dto, Modality modality, User creator) {
        return toEntity(dto, new ClassGroup(), modality, creator);
    }

    public static ClassGroupResponseDTO toResponse(ClassGroup classGroup, String nameCreator) {


        return new ClassGroupResponseDTO(
                classGroup.getId(),
                classGroup.getName(),
                classGroup.getCapacity(),
                classGroup.getGroupType().toString(),
                classGroup.getDescription(),
                ModalityMapper.toResponse(classGroup.getModality()),
                classGroup.getStartDate(),
                classGroup.getEndDate(),
                nameCreator
        );
    }



}
