package com.smarterfit.dto.request;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.util.Date;

import java.util.UUID;

public record ClassGroupRequestDTO(

        @NotNull(message = "User ID (creator) is required")
        UUID userCreatorId,

        @NotBlank(message = "Name is required")
        String title,

        @NotNull(message = "Capacity is required")
        @Min(value = 1, message = "Capacity must be at least 1")
        Integer capacity,

        @NotNull(message = "Group type is required")
        String groupType,

        @NotBlank(message = "Description is required")
        String description,

        @NotNull(message = "Modality ID is required")
        UUID modalityId,

        @NotNull(message = "Start date is required")
        @JsonFormat(pattern = "yyyy-MM-dd")
        Date startDate,

        @NotNull(message = "End date is required")
        @JsonFormat(pattern = "yyyy-MM-dd")
        Date endDate,

        @NotNull(message = "Auto-generated flag is required")
        Boolean autoGeneratedSessions
) {
}
