CREATE TABLE SF_USER (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    dt_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
