CREATE TABLE SF_USER (
    id UUID PRIMARY KEY,
    no_email VARCHAR(255) NOT NULL UNIQUE,
    no_username VARCHAR(255) NOT NULL UNIQUE,
    no_password VARCHAR(255) NOT NULL,
    dt_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dt_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
