package com.smarterfit.modules.classgroup.repository;

import com.smarterfit.modules.classgroup.entity.ClassGroup;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.smarterfit.modules.classgroup.entity.ClassGroupSchedule;
import org.springframework.data.repository.query.Param;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

public interface ClassGroupScheduleRepository extends JpaRepository<ClassGroupSchedule, UUID> {

    @Query("""
    SELECT CASE WHEN COUNT(cgs) > 0 THEN TRUE ELSE FALSE END
    FROM ClassGroupSchedule cgs
    WHERE cgs.classGroup.id = :classGroupId
      AND cgs.dayOfWeek = :dayOfWeek
      AND NOT (cgs.endTime <= :startTime OR cgs.startTime >= :endTime)
""")
    boolean existsOverlappingSchedule(
            @Param("classGroupId") UUID classGroupId,
            @Param("dayOfWeek") DayOfWeek dayOfWeek,
            @Param("startTime") LocalTime startTime,
            @Param("endTime") LocalTime endTime
    );

    @Query("""
        SELECT cgs FROM ClassGroupSchedule cgs
        WHERE cgs.classGroup.isActive = true
          AND cgs.classGroup.autoGeneratedSessions = true
          AND cgs.classGroup.endDate >= :today
    """)
    List<ClassGroupSchedule> findValidSchedules(@Param("today") LocalDate today);

}
