package com.smarterfit.modules.classgroup.dto.request.classgroup;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;

import java.time.LocalDate;
import java.util.UUID;

@Builder(toBuilder = true)
public record CreateClassGroupRequestDTO(

        @NotNull(message = "User ID (creator) is required")
        UUID userCreatorId,

        @NotBlank(message = "Name is required")
        String title,

        @NotNull(message = "Capacity is required")
        @Min(value = 1, message = "Capacity must be at least 1")
        Integer capacity,

        @NotBlank(message = "Description is required")
        String description,

        @NotNull(message = "Modality ID is required")
        UUID modalityId,

        @NotNull(message = "Start date is required")
        @JsonFormat(pattern = "dd-MM-yyyy")
        LocalDate startDate,

        @NotNull(message = "End date is required")
        @JsonFormat(pattern = "dd-MM-yyyy")
        LocalDate endDate,

        @NotNull(message = "Auto-generated flag is required")
        Boolean autoGeneratedSessions
) {
}
